Alter CRM document unique constraints
DEFRA/water-abstraction-tactical-crm pull request #1053
Opened 2024-10-14 14:04 UTC by jonathangoulding

https://eaflood.atlassian.net/browse/WATER-4708

As part of the ongoing work to move the import code into WRLS. We need to use constraints to enforce data consistency and uniqueness.

Previously the document type and regime where defaulted and used to form a unique key. We no longer need to do this.

This chance simplifies the unique constraint to just the document ref (licence ref).

2024-10-14 14:14 UTC, jonathangoulding commented
Running Acceptance test.

2024-10-14 16:18 UTC, jonathangoulding commented
> Running Acceptance test.

Still running...

2024-10-15 09:07 UTC, Cruikshanks requested changes
Just playing it safe, I'd suggest wrapping your migrations statements in a transaction.

2024-10-15 09:07 UTC, Cruikshanks commented on migrations/sqls/20241014133216-alter-crm-v2-documents-defaults.js-down.sql
> +create unique index documents_document_ref on crm_v2.documents(regime, document_type, document_ref);
Just to be on the safe side, I'd wrap both calls in a transaction.

```suggestion
BEGIN;

-- Drop unique index on the licence number
DROP INDEX crm_v2.documents_only_one_document_ref;

-- Create unique index on licence number
CREATE UNIQUE INDEX documents_document_ref ON crm_v2.documents(regime, document_type, document_ref);

COMMIT;
```

2024-10-15 09:07 UTC, Cruikshanks commented on migrations/sqls/20241014133216-alter-crm-v2-documents-defaults.js-up.sql
> +create unique index documents_only_one_document_ref on crm_v2.documents(document_ref);
```suggestion
BEGIN;

-- Drop unique index on licence number, document type and regime
DROP INDEX crm_v2.documents_document_ref;

-- -- Create unique index on licence number
CREATE UNIQUE INDEX documents_only_one_document_ref ON crm_v2.documents(document_ref);

COMMIT;
```

2024-10-15 10:46 UTC, Cruikshanks approved these changes

2024-10-15 10:47 UTC, merged